export enum StoryTypeEnum {
    Intro = 'INTRO',
    FavoriteTeam = 'FAVORITE_TEAM',
    FavoriteTeamList = 'FAVORITE_TEAM_LIST',
    LeastPreferedTeam = 'LEAST_PREFERED_TEAM',
    LuckiestWin = 'LUCKIEST_WIN',
    LuckiestWinList = 'LUCKIEST_WIN_LIST',
    BiggestWin = 'BIGGEST_WIN',
    BiggestWinList = 'BIGGEST_WIN_LIST',
    BiggestOdds = 'BIGGEST_ODDS',
    BiggestOddsList = 'BIGGEST_ODDS_LIST',
    BestDay = 'BEST_DAY',
    BestDayList = 'BEST_DAY_LIST',
    ContentCenter = 'CONTENT_CENTER',
    Thanks = 'THANKS',
}
